# Generated by Django 5.1.6 on 2025-04-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preview_image', models.ImageField(upload_to='previews/')),
                ('vector_file', models.FileField(upload_to='vectors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
