# Generated by Django 5.1.6 on 2025-05-06 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0002_vectordesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordesign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='VectorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vectores/')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='my_page.vectordesign')),
            ],
        ),
    ]
