# Generated by Django 5.1.6 on 2025-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0003_alter_vectordesign_description_vectorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordesign',
            name='description',
            field=models.TextField(),
        ),
    ]
