# Generated by Django 6.0.3 on 2026-06-17 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0005_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='download_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'design')},
        ),
    ]
