# Generated by Django 6.0.3 on 2026-06-23 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0007_course_coursepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='youtube_url',
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='my_page.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
