# Generated by Django 6.0.3 on 2026-09-23 14:53

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0008_remove_course_youtube_url_coursevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordesign',
            name='vector_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='vectors/'),
        ),
    ]
