# Generated by Django 6.0.3 on 2026-09-23 21:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_page', '0009_alter_vectordesign_vector_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='cursos/'),
        ),
    ]
